version: '3.4'
services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: FileHostingDb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - uploaded_files:/app/UploadedFiles
volumes:
  mongo_data:
  uploaded_files:
